### PR TITLE
Switch to make

### PR DESCRIPTION
**Pull request by voisardf**
And get rid of bootstrap/buildout

This PR also **removes** crdppf_core as a git submodule !!

### CODE REVIEW

**Comment by kalbermattenm** [comment]
image

Still quite a lot to do...

We should get ride of the war servlet in crdppf_core, because it makes the package almost undownloadable.

**Comment by kalbermattenm** [comment]
Remove `apache/application.wsgi` and add it to gitignore

**Comment by kalbermattenm** [comment]
I added the print section

**Comment by kalbermattenm** [comment]
`CONST_Makefile` & `CONST_vars.yaml` are now part of the core package.

**Comment by kalbermattenm** [comment]
I think where done.

@voisardf, please review.

We will have to add the core release once we have a proper release in the core package to the local crdppf `CONST_requirements.txt`

**Comment by kalbermattenm** [comment]
@voisardf, I cannot add you as reviewer because you opened this PR...

**Comment by kalbermattenm** [comment]
Needs to be updated with latest master state before merging

**Comment by voisardf** [comment]
Updated with master and backup done. Merging.
Bye, bye buildout!

**Comment by kalbermattenm** [comment]
+1

**Pull request merged**
